/*
 * @Author: JUN 
 * @Date: 2017-08-01 09:29:08 
 */
export default {
  GANK_CLEAR_NEWS: 'GANK_CLEAR_NEWS',
  GANK_RECEIVE_NEWS: 'GANK_RECEIVE_NEWS',
  GANK_CHANGE_NEWSTYPE: 'GANK_CHANGE_NEWSTYPE',
  //tab状态
  TABBAR_STAUST: 'TABBAR_STAUST'
}